/* 
   -------------------------------------------------------
   MY ULTIMATE CHRISTMAS PLAYLIST - SONG DATA
   -------------------------------------------------------
   1. Paste your specific YouTube video link inside the quotes "" next to 'url'.
   2. If you leave 'url' empty (""), the app will automatically create a search link.
*/

window.playlistData = [
    { title: "2000 miles", artist: "The Pretenders", url: "https://music.youtube.com/watch?v=sLvBbrWV7ZQ&si=1gsaBW3v7hZrn3wT" },
    { title: "All I Want For Christmas Is You", artist: "Mariah Carey", url: "https://music.youtube.com/watch?v=fRyhqobl0sk&si=N-7iNv0IzGEBryu2" },
    { title: "All I Want For Christmas Is You", artist: "Glee", url: "https://music.youtube.com/watch?v=fvr_nT3QcGY&si=MDh0q52QSudPwqyM" },
    { title: "Auld Lang Syne", artist: "Susan Boyle", url: "https://music.youtube.com/watch?v=6mJER3IGcnk&si=xwOjOF93rynkBBh4" },
    { title: "Baby Please Come Home", artist: "Darlene Love", url: "" },
    { title: "Baby, It's Cold Outside", artist: "Margaret Whiting · Johnny Mercer", url: "https://music.youtube.com/watch?v=j8n-WpfsstA&si=5mfMaCzYzD1EUwZp" },
    { title: "Blue Christmas", artist: "Elvis Presley", url: "https://music.youtube.com/watch?v=NqwENLwSTWQ&si=67s_86xhI_-rfptS" },
    { title: "Carol Of The Bells", artist: "The Harry Simeone Chorale", url: "" },
    { title: "Carol of the bells", artist: "John Williams", url: "https://music.youtube.com/watch?v=5zSfb5vmkPc&si=Xr2Qe8dBWd9QiH9c" },
    { title: "Christmas Wrapping", artist: "The Waitresses", url: "https://music.youtube.com/watch?v=ZYE7UJSA7k0&si=AN1vpBWlwdwWK6L6" },
    { title: "Deck the Halls", artist: "Brookyn Youth Orchestra, John Ceiriog Hughes", url: "" },
    { title: "Do They Know It's Christmas?", artist: "Band Aid", url: "https://music.youtube.com/watch?v=XsCbFpn7fDo&si=JxzSFgMcSK-RSYiV" },
    { title: "Driving Home For Christmas", artist: "Chris Rea", url: "https://music.youtube.com/watch?v=LVKB5Q8UAUk&si=urHoUSpm2X4aQhXH" },
    { title: "Fairytale Of New York", artist: "The Pogues", url: "https://music.youtube.com/watch?v=YBM156DuxvA&si=EziSbPX7bW76wR79" },
    { title: "Feliz Navidad", artist: "José Feliciano", url: "https://music.youtube.com/watch?v=jj-oTtHTwVY&si=gFCO-fP1ybWCHlOM" },
    { title: "Have Yourself A Merry Little Christmas", artist: "Frank Sinatra", url: "" },
    { title: "Frosty The Snowman", artist: "Bing Crosby", url: "https://music.youtube.com/watch?v=m-cNrbbT7_8&si=6ndzzpUyp-Gl6r_J" },
    { title: "Hallelujah", artist: "Alexandra Burke", url: "https://music.youtube.com/watch?v=YI1FBuXdf5U&si=BVdTycqE0kQEuLyW" },
    { title: "Happy New Year", artist: "ABBA", url: "https://music.youtube.com/watch?v=6eLnnZnXcX8&si=UUutDCOSGWqEDcqV" },
    { title: "Happy Xmas", artist: "Céline Dion", url: "https://music.youtube.com/watch?v=KtOqEzMUa4I&si=OZL5ooqQqwT41o0K" },
    { title: "Happy Xmas", artist: "John Lennon/The Harlem Community Choir", url: "" },
    { title: "Have Yourself a Merry Little Christmas", artist: "Sam Smith", url: "https://music.youtube.com/watch?v=pvA7-EjaSPI&si=rdZzLYTDE7qfL3g9" },
    { title: "Here Comes Santa Claus", artist: "Elvis Presley", url: "https://music.youtube.com/watch?v=MKSdxDAg8Tw&si=WD1tlw29D9ApnSAF" },
    { title: "Holly Jolly Christmas", artist: "Burl Ives", url: "https://music.youtube.com/watch?v=NOBmGcepcTI&si=0TLvjLc5oNBOLVJg" },
    { title: "I Believe In Father Christmas", artist: "Greg Lake", url: "https://music.youtube.com/watch?v=odHx4URivtE&si=1v1K4nAMxzWuYasB" },
    { title: "I Saw Mommy Kissing Santa Claus", artist: "The Jackson 5", url: "https://music.youtube.com/watch?v=U5resSXzMiI&si=-TrddPsD9fpyI1dD" },
    { title: "I Wish It Could Be Christmas Everyday", artist: "Girls Aloud", url: "https://music.youtube.com/watch?v=eXj6Z8jmxFI&si=J8SFpXUFDM2QjvjV" },
    { title: "I'll Be Home for Christmas", artist: "Doris Day", url: "https://music.youtube.com/watch?v=tItGjgFZpjk&si=ZNe1X2QneWn4swK6" },
    { title: "It's Beginning to Look a Lot Like Christmas", artist: "Bing Crosby", url: "https://music.youtube.com/watch?v=Koz5ofCptJw&si=CGjKtUWaam-4FXWe" },
    { title: "It's The Most Wonderful Time Of The Year", artist: "Andy Williams", url: "https://music.youtube.com/watch?v=9JQU_3Mx6xY&si=NJnmyGXeOye_LIbb" },
    { title: "Jingle Bell Rock", artist: "Bobby Helms", url: "https://music.youtube.com/watch?v=Qe1Bj7qIang&si=kqSycIdA1WwJUWzM" },
    { title: "Last Christmas", artist: "Wham", url: "https://music.youtube.com/watch?v=GJvGf_ifiKw&si=xC5rzsYH3qDQ0boM" },
    { title: "Let It Snow! Let It Snow! Let It Snow!", artist: "Dean Martin", url: "https://music.youtube.com/watch?v=tZmY4L4cfus&si=0-20gh9eOWaF4gCz" },
    { title: "Little Drummer Boy", artist: "Pentatonix", url: "https://music.youtube.com/watch?v=KYiUSalSjS0&si=Wq-BNBqEDK0YHuW-" },
    { title: "Little Saint Nick", artist: "The Beach Boys", url: "https://music.youtube.com/watch?v=5dyXN74aZGQ&si=Vueg1MRqIdzVb-vr" },
    { title: "Lonely This Christmas", artist: "Mabel", url: "https://music.youtube.com/watch?v=6B80OlHTCxg&si=Lkz6cq21tAjnG-_n" },
    { title: "Mary's Boy Child / Oh My Lord", artist: "Boney M.", url: "https://music.youtube.com/watch?v=sNmQCmJ2_ZE&si=5tPH3WExP3k00mHK" },
    { title: "Mele Kalikimaka", artist: "Bing Crosby & The Andrews Sisters", url: "https://music.youtube.com/watch?v=BtdEufWBDo8&si=7Pi2zH0bd_7zf4by" },
    { title: "Merry Christmas Everyone", artist: "Shakin' Stevens", url: "https://music.youtube.com/watch?v=ectgjkpq6As&si=fQORC10RCF_Hs18j" },
    { title: "Merry Xmas Everybody", artist: "Slade", url: "https://music.youtube.com/watch?v=88WsYBGmrjI&si=a4LsbOnqRpZ1-5gc" },
    { title: "Mistletoe", artist: "Justin Bieber", url: "https://music.youtube.com/watch?v=g-HR0e4gLzQ&si=68p89hkyqX3UT9h5" },
    { title: "Mistletoe And Wine", artist: "Cliff Richard", url: "https://music.youtube.com/watch?v=L9HtT-jShi0&si=zwPUQGKDto8Y6RmI" },
    { title: "O Holy Night", artist: "Mariah Carey", url: "https://music.youtube.com/watch?v=3r_3P0wSSFg&si=o2BZshnbsfAY-a0K" },
    { title: "One More Sleep", artist: "Leona Lewis", url: "https://music.youtube.com/watch?v=3r_3P0wSSFg&si=o2BZshnbsfAY-a0K" },
    { title: "Rockin' Around the Christmas Tree", artist: "Brenda Lee", url: "https://music.youtube.com/watch?v=O1x-hOOrl5E&si=zKdrGtXexnSGGMwI" },
    { title: "Rudolph The Red Nosed Reindeer", artist: "Gene Autry", url: "" },
    { title: "Santa Baby", artist: "Eartha Kitt", url: "https://music.youtube.com/watch?v=QFx3MWkn3Zo&si=L6HukH0HRSnVgpy4" },
    { title: "Santa Claus Is Comin' To Town", artist: "Mariah Carey", url: "https://music.youtube.com/watch?v=hi_LZcMo47U&si=YTbBWY-p_7qXLv4w" },
    { title: "Santa Claus Is Coming to Town", artist: "The Jackson 5", url: "https://music.youtube.com/watch?v=nYmPZrvThW8&si=gXZGcRea2EPavhyh" },
    { title: "Santa Tell Me", artist: "Ariana Grande", url: "https://music.youtube.com/watch?v=2TEAh5SHZGs&si=w1nO3uD_53ul9TdP" },
    { title: "Santa's Coming For Us", artist: "Sia", url: "https://music.youtube.com/watch?v=l8JSq9BJwM8&si=zh8RVp1rZ1Kq7zau" },
    { title: "Silent Night", artist: "Frank Sinatra", url: "" },
    { title: "Silent Night", artist: "Michael Bublé", url: "" },
    { title: "Sleigh Ride", artist: "The Ronettes", url: "https://music.youtube.com/watch?v=oH4WG1x_KR8&si=XcR34zNbi1x9_eCp" },
    { title: "Step Into Christmas", artist: "Elton John", url: "" },
    { title: "Stop the Cavalry", artist: "Jona Lewie", url: "https://music.youtube.com/watch?v=jnc8166dPeY&si=OLKoUm5aBROUoV-U" },
    { title: "Thank God It's Christmas", artist: "Queen", url: "https://music.youtube.com/watch?v=-BhIPx2gQW0&si=s62292Q3FmXUdbTP" },
    { title: "The Christmas Song", artist: "Nat King Cole", url: "https://music.youtube.com/watch?v=1Jp3XIqTR2w&si=d819HqNBOmGbHDUe" },
    { title: "The Little Drummer Boy", artist: "Bing Crosby", url: "https://music.youtube.com/watch?v=cag2FvYwuZs&si=3jlptO54TnO7FGOh" },
    { title: "Underneath the Tree", artist: "Kelly Clarkson", url: "https://music.youtube.com/watch?v=IuaW6w3Mh4c&si=0USaI3aRvqr8vMFR" },
    { title: "We Wish You a Merry Christmas", artist: "The Weavers", url: "" },
    { title: "White Christmas", artist: "Bing Crosby", url: "https://music.youtube.com/watch?v=t_xq3Bj_tas&si=VzgEQDlCduh7JSHm" },
    { title: "White Christmas", artist: "Michael Bublé", url: "https://music.youtube.com/watch?v=qhMS8ij1fsg&si=-thb82mUaEPP4fE7" },
    { title: "Winter Wonderland", artist: "Tony Bennett", url: "" },
    { title: "Wonderful Christmas time", artist: "Paul McCartney", url: "" }
];