/**
 * Markdown Editor AI proxy.
 * GEMINI_API_KEY stays in the server environment. The browser sends the
 * signed-in Drive access token only so this route can check who is calling.
 */

export const config = {
    runtime: 'edge',
    maxDuration: 60,
};

const MODEL = 'gemini-2.5-flash-lite';
/** Exact Google account. Dots and plus-aliases do not match. */
const ALLOWED_EMAIL = 'xanderwiles@gmail.com';
const MAX_MARKDOWN = 400_000;
const MAX_SELECTION = 20_000;
const MAX_INSTRUCTION = 4_000;
const TASKS = new Set(['expand', 'header', 'summarize', 'revise', 'edit', 'context']);
const MAX_CONTEXT_FILES = 4;

const SYSTEM = `You edit one Markdown note.
Return only the requested Markdown. No preamble and no closing comment.
Preserve every mdlist fence exactly, including its JSON and the HTML comment above it.
Preserve every {{date:...}} tag unless the task explicitly asks to add one.
Do not wrap the whole answer in a code fence.
CONTEXT files are read-only. Change only the note marked EDIT.`;

const CONTEXT_SYSTEM = `The attached Markdown is reference only.
Answer the user's question in plain sentences or a short Markdown reply.
Do not return the full file. Do not claim the file was changed.`;

function json(body, status) {
    return new Response(JSON.stringify(body), {
        status,
        headers: { 'Content-Type': 'application/json' },
    });
}

function todayIso() {
    return new Date().toISOString().slice(0, 10);
}

function contextBlock(files) {
    if (!files.length) return '';
    return files
        .map(
            (file, index) =>
                `CONTEXT ${index + 1} (${file.name}) — do not edit this file:\n${file.markdown}`
        )
        .join('\n\n');
}

function buildInput({ task, markdown, selection, instruction, contextFiles }) {
    const context = contextBlock(contextFiles);
    const note = task === 'context' ? '' : `EDIT THIS FILE ONLY:\n${markdown}`;
    const extra = instruction ? `\nINSTRUCTION:\n${instruction}\n` : '';
    if (task === 'context') {
        return [context, extra].filter(Boolean).join('\n\n');
    }
    if (task === 'expand') {
        return [
            'Expand the selection into Markdown that fits the surrounding note.',
            'Return only the replacement for the selection, not the whole note.',
            '',
            'SELECTION:',
            selection,
            extra,
            context,
            note,
        ].filter(Boolean).join('\n\n');
    }
    if (task === 'header') {
        return [
            `Write a note header: one H1, one {{date:${todayIso()}}} tag, and one summary paragraph.`,
            'Do not repeat the rest of the note.',
            extra,
            context,
            note,
        ].filter(Boolean).join('\n\n');
    }
    if (task === 'summarize') {
        return [
            'Write a ## Summary section with 3 to 6 bullets describing the note.',
            'Do not include mdlist fences or copy the whole note.',
            extra,
            context,
            note,
        ].filter(Boolean).join('\n\n');
    }
    return [
        'Apply the instruction to the EDIT file only.',
        'Return the full revised EDIT file as Markdown.',
        extra,
        context,
        note,
    ].filter(Boolean).join('\n\n');
}

function outputText(interaction) {
    if (typeof interaction?.output_text === 'string' && interaction.output_text.trim()) {
        return interaction.output_text;
    }
    const steps = Array.isArray(interaction?.steps) ? interaction.steps : [];
    const chunks = [];
    for (const step of steps) {
        if (step?.type !== 'model_output') continue;
        const content = step.content;
        if (typeof content === 'string') {
            chunks.push(content);
            continue;
        }
        if (!Array.isArray(content)) continue;
        for (const block of content) {
            if (typeof block === 'string') chunks.push(block);
            else if (block?.type === 'text' && block.text) chunks.push(block.text);
        }
    }
    return chunks.join('');
}

async function callerEmail(accessToken) {
    const response = await fetch(
        'https://www.googleapis.com/drive/v3/about?fields=user(emailAddress)',
        { headers: { Authorization: `Bearer ${accessToken}` } }
    );
    if (response.status === 401 || response.status === 403) {
        return { error: 'Sign in again to use AI.', status: 401 };
    }
    if (!response.ok) {
        return { error: 'Could not verify the signed-in Drive account.', status: 502 };
    }
    const data = await response.json().catch(() => ({}));
    const email = String(data?.user?.emailAddress || '').trim().toLowerCase();
    if (!email) {
        return { error: 'Could not read the signed-in account email.', status: 401 };
    }
    return { email };
}

export default async function handler(request) {
    if (request.method !== 'POST') {
        return json({ error: 'Method not allowed' }, 405);
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
        return json(
            { error: 'GEMINI_API_KEY is not set on the server.' },
            500
        );
    }

    const header = request.headers.get('authorization') || '';
    const accessToken = header.startsWith('Bearer ') ? header.slice(7).trim() : '';
    if (!accessToken) {
        return json({ error: 'Sign in again to use AI.' }, 401);
    }

    const who = await callerEmail(accessToken);
    if (who.error) return json({ error: who.error }, who.status);
    if (who.email !== ALLOWED_EMAIL) {
        return json({ error: 'This account cannot use AI mode.' }, 403);
    }

    let body;
    try {
        body = await request.json();
    } catch {
        return json({ error: 'Expected a JSON body.' }, 400);
    }

    const task = String(body?.task || '');
    const markdown = String(body?.markdown ?? '');
    const selection = String(body?.selection ?? '');
    const instruction = String(body?.instruction ?? '').trim();
    const contextFiles = normalizeContextFiles(body?.contextFiles);

    if (!TASKS.has(task)) return json({ error: 'Unknown AI task.' }, 400);
    if (contextFiles.error) return json({ error: contextFiles.error }, contextFiles.status);
    if (task !== 'context' && !markdown.trim()) return json({ error: 'The note is empty.' }, 400);
    if (task === 'context' && !markdown.trim() && !contextFiles.files.length) {
        return json({ error: 'Attach a note to use as context.' }, 400);
    }
    if (markdown.length > MAX_MARKDOWN) {
        return json({ error: 'This note is too large to send.' }, 413);
    }
    if (selection.length > MAX_SELECTION) {
        return json({ error: 'That passage is too long.' }, 413);
    }
    if (instruction.length > MAX_INSTRUCTION) {
        return json({ error: 'That instruction is too long.' }, 413);
    }
    if (task === 'expand' && !selection.trim()) {
        return json({ error: 'Add the passage to expand.' }, 400);
    }
    if ((task === 'revise' || task === 'edit' || task === 'context') && !instruction) {
        return json({ error: 'Describe what should change.' }, 400);
    }

    let gemini;
    try {
        gemini = await fetch('https://generativelanguage.googleapis.com/v1beta/interactions', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'x-goog-api-key': apiKey,
                'Api-Revision': '2026-05-20',
            },
            body: JSON.stringify({
                model: MODEL,
                store: false,
                system_instruction: task === 'context' ? CONTEXT_SYSTEM : SYSTEM,
                generation_config: {
                    thinking_level: 'minimal',
                },
                input: buildInput({
                    task,
                    markdown,
                    selection,
                    instruction,
                    contextFiles: contextFiles.files,
                }),
            }),
            signal: AbortSignal.timeout(50_000),
        });
    } catch {
        return json({ error: 'Gemini did not respond in time.' }, 504);
    }

    const payload = await gemini.json().catch(() => ({}));
    if (!gemini.ok) {
        const message = payload?.error?.message || `Gemini request failed (${gemini.status})`;
        return json({ error: message }, gemini.status === 429 ? 429 : 502);
    }
    if (payload.status && payload.status !== 'completed') {
        return json({ error: 'Gemini did not finish the edit.' }, 502);
    }

    const markdownOut = outputText(payload).trim();
    if (!markdownOut) {
        return json({ error: 'Gemini returned an empty response.' }, 502);
    }
    if (task === 'context') return json({ reply: markdownOut }, 200);
    return json({ markdown: markdownOut }, 200);
}

function normalizeContextFiles(value) {
    if (value == null) return { files: [] };
    if (!Array.isArray(value)) return { error: 'Context files were not a list.', status: 400 };
    if (value.length > MAX_CONTEXT_FILES) {
        return { error: 'Attach at most 4 context notes.', status: 413 };
    }
    const files = [];
    let total = 0;
    for (const entry of value) {
        const name = String(entry?.name || 'note.md').slice(0, 180);
        const markdown = String(entry?.markdown ?? '');
        total += markdown.length;
        if (markdown.length > MAX_MARKDOWN || total > MAX_MARKDOWN) {
            return { error: 'The attached notes are too large to send.', status: 413 };
        }
        if (markdown.trim()) files.push({ name, markdown });
    }
    return { files };
}
